import type { WineType, FlavorProfile, ShopConfig } from './types'

export const WINE_TYPES: { value: WineType; label: string }[] = [
  { value: 'red', label: 'Rood' },
  { value: 'white', label: 'Wit' },
  { value: 'rose', label: 'Ros\u00e9' },
  { value: 'sparkling', label: 'Mousserende' },
  { value: 'dessert', label: 'Dessert & Port' },
]

export const GRAPES = [
  'Cabernet Sauvignon',
  'Merlot',
  'Pinot Noir',
  'Syrah/Shiraz',
  'Tempranillo',
  'Sangiovese',
  'Nebbiolo',
  'Malbec',
  'Zinfandel',
  'Grenache/Garnacha',
  'Mourvèdre',
  'Barbera',
  'Carménère',
  'Pinotage',
  'Primitivo',
  'Petit Verdot',
  'Cabernet Franc',
  'Gamay',
  'Touriga Nacional',
  'Montepulciano',
  'Chardonnay',
  'Sauvignon Blanc',
  'Riesling',
  'Pinot Grigio/Pinot Gris',
  'Gewürztraminer',
  'Viognier',
  'Chenin Blanc',
  'Sémillon',
  'Muscat/Moscato',
  'Grüner Veltliner',
  'Albariño',
  'Verdejo',
  'Torrontés',
  'Vermentino',
  'Trebbiano',
  'Garganega',
  'Fiano',
  'Assyrtiko',
  'Godello',
  'Marsanne',
  'Roussanne',
  'Melon de Bourgogne',
] as const

export const FLAVORS: { value: FlavorProfile; label: string }[] = [
  { value: 'fruity', label: 'Fruitig' },
  { value: 'dry', label: 'Droog' },
  { value: 'tannic', label: 'Tannine-rijk' },
  { value: 'oaky', label: 'Eikenhout' },
  { value: 'mineral', label: 'Mineraal' },
  { value: 'spicy', label: 'Kruidig' },
  { value: 'floral', label: 'Bloemig' },
  { value: 'earthy', label: 'Aards' },
]

export const COUNTRIES = [
  { value: 'france', label: 'Frankrijk' },
  { value: 'italy', label: 'Italië' },
  { value: 'spain', label: 'Spanje' },
  { value: 'portugal', label: 'Portugal' },
  { value: 'germany', label: 'Duitsland' },
  { value: 'austria', label: 'Oostenrijk' },
  { value: 'greece', label: 'Griekenland' },
  { value: 'usa', label: 'Verenigde Staten' },
  { value: 'argentina', label: 'Argentinië' },
  { value: 'chile', label: 'Chili' },
  { value: 'australia', label: 'Australië' },
  { value: 'new-zealand', label: 'Nieuw-Zeeland' },
  { value: 'south-africa', label: 'Zuid-Afrika' },
  { value: 'hungary', label: 'Hongarije' },
  { value: 'romania', label: 'Roemenië' },
] as const

export const SHOP_CONFIGS: ShopConfig[] = [
  {
    slug: 'wijnvoordeel',
    name: 'Wijnvoordeel',
    baseUrl: 'https://www.wijnvoordeel.nl',
    enabled: true,
    description: 'Sinds 1999 online gerenommeerde wijnen voor spectaculair lage prijzen. Meer dan 350 wijnen uit alle toonaangevende wijngebieden.',
  },
  {
    slug: 'wijnbeurs',
    name: 'Wijnbeurs',
    baseUrl: 'https://www.wijnbeurs.nl',
    enabled: true,
    description: 'Al 48 jaar de meest bijzondere wijnen, direct bij de wijnboer ingekocht. Blind geproefd voor gegarandeerde kwaliteit.',
  },
  {
    slug: 'gall',
    name: 'Gall & Gall',
    baseUrl: 'https://www.gall.nl',
    enabled: true,
    description: 'De bekendste slijterij van Nederland met ruim 600 winkels. Groot assortiment wijn, bier en sterke drank.',
  },
  {
    slug: 'drankdozijn',
    name: 'DrankDozijn',
    baseUrl: 'https://www.drankdozijn.nl',
    enabled: true,
    description: 'Dé online slijterij van Nederland met meer dan 4.000 producten. Breed assortiment wijn, whisky, rum, gin en meer.',
  },
  {
    slug: 'viavina',
    name: 'Viavina',
    baseUrl: 'https://www.viavina.nl',
    enabled: true,
    description: 'Mindfully crafted biologische en natuurzuivere wijnen zonder toegevoegde suikers.',
  },
  {
    slug: 'fanster',
    name: 'Fanster',
    baseUrl: 'https://www.fanster.nl',
    enabled: true,
    description: 'Meer dan 800 wijnen van over de hele wereld onder één dak. Alle wijnen in huis voor snelle levering.',
  },
  {
    slug: 'topdrinks',
    name: 'Topdrinks',
    baseUrl: 'https://www.topdrinks.nl',
    enabled: true,
    description: 'Uitgebreid aanbod dranken met scherpe prijzen. Van bekende likeuren tot exclusieve whiskeys en wijnen.',
  },
  {
    slug: 'drinkheroes',
    name: 'Drink Heroes',
    baseUrl: 'https://www.drinkheroes.nl',
    enabled: true,
    description: 'Gepassioneerde wijnspecialist met topwijnen in rood, wit, rosé, mousserende en alcoholvrij.',
  },
  {
    slug: 'dewijngoeroe',
    name: 'De Wijngoeroe',
    baseUrl: 'https://www.dewijngoeroe.nl',
    enabled: true,
    description: 'Wijnexpert met zorgvuldig geselecteerde wijnen. Persoonlijk advies en kwaliteitswijnen.',
  },
]

export const ENABLED_SHOP_COUNT = SHOP_CONFIGS.filter(s => s.enabled).length

export const SCORING_WEIGHTS = {
  grape: 30,
  region: 20,
  type: 15,
  flavor: 15,
  price: 10,
  rating: 10,
} as const
